/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'processing' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const OrderRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'items' : IDL.Vec(OrderItem),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(OrderRecord)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [IDL.Nat], []),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'processing' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const OrderRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'items' : IDL.Vec(OrderItem),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(OrderRecord)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [IDL.Nat], []),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'updateCartItem' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  });
};

export const init = ({ IDL }) => { return []; };